export const defaultLocation = {
  id: "costa-mesa",
  name: "Pronto Costa Mesa",
  addressLines: ["1847 Harbor Blvd.", "Costa Mesa, CA 92627"],
  phone: "(714) 555-0184",
  hours: "Daily: 5am-8pm",
  serviceModel: "Cafe + Pickup",
};

export const menuCategories = [
  {
    id: "handcrafted",
    title: "Handcrafted Drinks",
    description: "Signature espresso drinks, house flavors, and smooth coffee favorites.",
    staffLabel: "Coffee",
    items: [
      {
        id: "house-latte",
        name: "House Latte",
        description: "Espresso, milk, and Pronto vanilla bean syrup.",
        price: "$6.25",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
        bestSeller: true,
      },
      {
        id: "maple-sea-salt-latte",
        name: "Maple Sea Salt Latte",
        description: "Espresso with maple syrup, flaky sea salt, and velvety milk.",
        price: "$6.75",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
      {
        id: "mocha-latte",
        name: "Mocha Latte",
        description: "Espresso, dark chocolate, and steamed milk.",
        price: "$6.95",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
      {
        id: "honey-cinnamon-latte",
        name: "Honey Cinnamon Latte",
        description: "Espresso sweetened with wildflower honey and cinnamon.",
        price: "$6.65",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
    ],
  },
  {
    id: "espresso",
    title: "Espresso Bar",
    description: "The daily coffee staples, pulled clean and built to order.",
    staffLabel: "Espresso",
    items: [
      {
        id: "americano",
        name: "Americano",
        description: "Double espresso finished with hot water.",
        price: "$4.25",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Dairy-Free", "Vegan"],
        temperatureOptions: ["Hot", "Iced"],
      },
      {
        id: "cappuccino",
        name: "Cappuccino",
        description: "Espresso with textured milk and a fluffy cap.",
        price: "$5.25",
        sizes: ["Small", "Medium"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
      {
        id: "flat-white",
        name: "Flat White",
        description: "Ristretto espresso with silky milk.",
        price: "$5.75",
        sizes: ["Small", "Medium"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
      {
        id: "cortado",
        name: "Cortado",
        description: "Equal parts espresso and warm milk.",
        price: "$4.95",
        sizes: ["Small"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
    ],
  },
  {
    id: "cold",
    title: "Cold Brew + Iced Coffee",
    description: "Bright, chilled, and built for quick pickup.",
    staffLabel: "Cold",
    items: [
      {
        id: "cold-brew",
        name: "Cold Brew",
        description: "Slow-steeped coffee poured over ice.",
        price: "$5.25",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Dairy-Free", "Vegan"],
        temperatureOptions: ["Iced"],
        bestSeller: true,
      },
      {
        id: "vanilla-cream-cold-brew",
        name: "Vanilla Cream Cold Brew",
        description: "Cold brew topped with sweet vanilla cream.",
        price: "$5.95",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Iced"],
      },
      {
        id: "brown-sugar-shakerato",
        name: "Brown Sugar Shakerato",
        description: "Espresso shaken with brown sugar and oat milk.",
        price: "$6.50",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Dairy-Free", "Vegan"],
        temperatureOptions: ["Iced"],
        milkOptions: ["Oat", "Almond", "Soy"],
      },
      {
        id: "citrus-tonic-cold-brew",
        name: "Citrus Tonic Cold Brew",
        description: "Cold brew, tonic water, and orange peel.",
        price: "$6.10",
        sizes: ["Medium", "Large"],
        dietaryTags: ["Dairy-Free", "Vegan"],
        temperatureOptions: ["Iced"],
        seasonal: true,
      },
    ],
  },
  {
    id: "tea",
    title: "Tea + More",
    description: "Tea lattes, matcha, and refreshing non-coffee options.",
    staffLabel: "Tea",
    items: [
      {
        id: "matcha-latte",
        name: "Matcha Latte",
        description: "Ceremonial matcha whisked with milk.",
        price: "$6.35",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
        bestSeller: true,
      },
      {
        id: "chai-latte",
        name: "Chai Latte",
        description: "Spiced black tea concentrate with steamed milk.",
        price: "$5.95",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
      {
        id: "lavender-tea-latte",
        name: "Lavender Tea Latte",
        description: "Floral black tea with lavender syrup and milk.",
        price: "$6.15",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Vegetarian"],
        temperatureOptions: ["Hot", "Iced"],
        milkOptions: ["Whole", "Oat", "Almond", "Soy"],
      },
      {
        id: "strawberry-lemon-spritz",
        name: "Strawberry Lemon Spritz",
        description: "House strawberry puree, lemon, and sparkling water.",
        price: "$5.85",
        sizes: ["Small", "Medium", "Large"],
        dietaryTags: ["Dairy-Free", "Vegan"],
        temperatureOptions: ["Iced"],
        seasonal: true,
      },
    ],
  },
  {
    id: "breakfast",
    title: "Breakfast Sandwiches + Toasts",
    description: "Savory favorites that pair well with the morning coffee run.",
    staffLabel: "Food",
    items: [
      {
        id: "pronto-breakfast-sandwich",
        name: "Pronto Breakfast Sandwich",
        description: "Egg, sharp cheddar, bacon, and garlic aioli on a toasted brioche bun.",
        price: "$10.95",
        dietaryTags: ["Contains Egg"],
      },
      {
        id: "ham-cheese-croissant",
        name: "Ham + Cheese Croissant",
        description: "Smoked ham and melty swiss on a buttery croissant.",
        price: "$9.25",
        dietaryTags: ["Contains Gluten"],
        bestSeller: true,
      },
      {
        id: "avocado-toast",
        name: "Avocado Toast",
        description: "Smashed avocado, chili flake, lemon, and herbs on thick-cut sourdough.",
        price: "$9.75",
        dietaryTags: ["Vegetarian"],
      },
      {
        id: "turkey-pesto-toastie",
        name: "Turkey Pesto Toastie",
        description: "Turkey, mozzarella, pesto, and tomato on pressed ciabatta.",
        price: "$11.25",
        dietaryTags: ["Contains Gluten"],
      },
    ],
  },
  {
    id: "pastries",
    title: "Pastries + Sweet Things",
    description: "Counter treats for quick add-ons and afternoon stops.",
    staffLabel: "Pastry",
    items: [
      {
        id: "butter-croissant",
        name: "Butter Croissant",
        description: "Flaky, buttery, and baked fresh each morning.",
        price: "$4.25",
        dietaryTags: ["Vegetarian"],
      },
      {
        id: "blueberry-muffin",
        name: "Blueberry Muffin",
        description: "Tender muffin with a sugared top and plenty of berries.",
        price: "$4.65",
        dietaryTags: ["Vegetarian"],
      },
      {
        id: "cinnamon-coffee-cake",
        name: "Cinnamon Coffee Cake",
        description: "Crumb-topped cake made for a drip coffee pairing.",
        price: "$4.95",
        dietaryTags: ["Vegetarian"],
      },
      {
        id: "seasonal-cookie",
        name: "Seasonal Bakery Cookie",
        description: "Rotating bakery cookie from the pastry case.",
        price: "$3.95",
        dietaryTags: ["Vegetarian"],
        seasonal: true,
      },
    ],
  },
];

export const featuredMenuItems = [
  {
    name: "House Latte",
    category: "Handcrafted Drinks",
    image: "/assets/images/coffee_hero.png",
    callout: "Best Seller",
    blurb: "Vanilla bean, espresso, and silky milk for the all-day regular.",
  },
  {
    name: "Cold Brew",
    category: "Cold Brew + Iced Coffee",
    image: "/assets/images/coffee_growth.png",
    callout: "Daily Favorite",
    blurb: "Bold, bright, and built for quick pickup on the way in.",
  },
  {
    name: "Pronto Breakfast Sandwich",
    category: "Breakfast Sandwiches + Toasts",
    image: "/assets/images/work_1.jpg",
    callout: "Morning Pairing",
    blurb: "Egg, cheddar, bacon, and garlic aioli on toasted brioche.",
  },
];

export const seasonalHighlights = [
  "Citrus Tonic Cold Brew",
  "Strawberry Lemon Spritz",
  "Seasonal Bakery Cookie",
];

export const orderingCategories = menuCategories.map((category) => ({
  id: category.id,
  title: category.title,
  staffLabel: category.staffLabel,
  items: category.items.map((item) => ({
    id: item.id,
    name: item.name,
    basePrice: item.price,
    category: category.staffLabel,
    sizes: item.sizes || [],
    milkOptions: item.milkOptions || [],
    temperatureOptions: item.temperatureOptions || [],
    dietaryTags: item.dietaryTags || [],
  })),
}));

export function formatOrderItem(item, selections = {}) {
  const parts = [];
  if (selections.size) parts.push(selections.size);
  if (selections.temperature) parts.push(selections.temperature);
  parts.push(item.name);
  if (selections.milk) parts.push(`with ${selections.milk} milk`);
  return parts.join(" ");
}
